# Sets Travis to run the Ruby specs on OS X machines to be as close as possible
# to the user environment.
#
osx_image: xcode7.3
language: objective-c
cache: bundler
rvm:
  - system
  - 2.0.0-p451

addons:
 code_climate:
   repo_token: 937468c2cbb0d7c0546b62d0fcbcba8a2a8b82714a64a52ffd0b951e71df626d

before_install:
  - export GEM_HOME=$HOME/.gem
  - export PATH=$GEM_HOME/bin:$PATH
  - sudo gem install bundler

install:
  - bundle install --without=documentation

script: bundle exec rake spec
